# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [2]:
import numpy as np
import itertools


def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def index_perm(n):
    """
    The function generate list with permutations of index 
    """
    P = []
    for i in range(0, n):
        P.append(i)
    t = list(itertools.permutations(P, n))
    """t - список перестановок других індексів множників"""
    for j in range(0, len(t)):
        t[j] = list(t[j])
    return t

def perm(t, M):
    """
    The function generate list with permutations of multipliers
    """
    A = []
    for i in range(0, len(t)):
        A_index = []
        for j in range(0, len(t[i])):
            A_index.append(M[j][t[i][j]])
        A.append(A_index)    
    return A

def bubble(X, Y, n):
    """
    The function counts number of inversion
    """
    if n > 2:
        for k in range(0, len(X)):
            
            flagok = True
            inversion = 0  
            while(flagok):
                i = 0
                flagok = False
                for i in range(0, len(X[k]) - 1):
                    if(X[k][i]>X[k][i + 1]):
                        temp = X[k][i]
                        X[k][i] = X[k][i + 1]
                        X[k][i + 1] = temp
                        flagok = True
                        inversion = inversion + 1
            Y[k].append((-1)**inversion)
    return Y

def mnozhennia(X):
    """
    This function performs multiplication of elements of terms
    """
    Y = []
    for i in range(0, len(X)):
        Mnozh = 1
        for j in range(0, len(X[i])):
            Mnozh = Mnozh * X[i][j]
        Y.append(Mnozh)
    return Y

def Sum(Y):
    """
    This function performs the addition of terms
    """
    Suma = 0
    for i in Y:
        Suma = Suma + i
    return Suma

"""
det(A) = SUM((-1)^g * a[1][i1]*a[2][i2]*.....*a[n][in])
g - number of inversion in permutation: i1, i2, i3, ..... in

"""
n = int(input("Введiть розмiрнiсть матрицi: "))
M = random_matrix(n)
print(M)
print("\033[35m\033[1mMy determinant =\033[0m", Sum(mnozhennia(bubble(index_perm(n), perm(index_perm(n), M), n))))
print("\033[32m\033[1mTrue determinant =\033[0m", np.linalg.det(M))

[[0 6 7 6 3 5 0 4 8]
 [6 6 5 9 2 9 6 4 3]
 [9 9 5 4 6 1 9 5 2]
 [4 7 5 3 3 4 4 5 6]
 [4 1 1 2 5 0 4 7 3]
 [3 2 2 0 6 4 0 1 1]
 [5 0 9 1 9 7 9 1 3]
 [9 5 1 6 8 4 6 6 3]
 [2 7 3 1 0 9 5 1 2]]
My determinant = 12648595
True determinant = 12648594.999999998
